endpoint = "https://porkbun.com/api/json/v3"
endpointv4 = "https://api-ipv4.porkbun.com/api/json/v3"

# If true, only use IPv6. Otherwise, attempts dual-stack and falls back to v4 only.
v6only = false

[keys]
apikey = "pk1_ your api key"
secretapikey = "sk1_ your secret key"

[domain]
root = "example.com"
sub = "foo" # Set to "" if you want to set the root domain!